base-url=""
debug=true
db-path="./db"
https_domain-whitelist=["localhost"]
http-addr=":8080"
parser-refresh-interval="12h"
persist-marketdata=true
sso-authorize-url="https://login.eveonline.com/oauth/authorize"
sso-client-id=""
sso-client-secret=""
sso-token-url="https://login.eveonline.com/oauth/token"
sso-verify-url="https://login.eveonline.com/oauth/verify"
ssl-cert=""
ssl-key=""
static-cache-control="public, max-age=3600"
ui="web"
